title: Hello, world! I'm 陈景澄
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weiherty.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: chenjingcheng # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a Driver Software Engineer focusing on Android telephone. Always hungry to keep learning. # add description
twitter: weiherty # add your Twitter handle
facebook: weiherty # add your Facebook handle
github: weiherty # add your Github handle
linkedin: weiherty # add your Linkedin handle
email: weiherty@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
